name: Publish to package registry

on:
  release:
    types:
    - published

jobs:
  npm_registry:
    name: npm Registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Setup Node.js
      uses: actions/setup-node@master
      with:
        node-version: '14.x'

    - name: Install npm dependencies
      run: npm ci

    - name: Build library
      run: npx tsc

    - name: Set npm registry
      run: npm config set registry https://registry.npmjs.org

    - name: Publish package
      run: npx npm-deploy-git-tag --access public --token ${{ secrets.NPM_TOKEN }}
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
